# ***📌Portfolio Project 2***



***Мета проекту*** - проаналізувати результати A/B-тестування за допомогою статистичних методів в Python та створити візуалізацію, що демонструє ключові конверсійні метрики.


**Етап 1. Розрахунок статистичної значущості.**

Розрахунок статистичної значущісті для чотирьох метрик:

* add_payment_info / session

* add_shipping_info / session

* begin_checkout / session

* new_accounts / session

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy import stats
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
file_path = '/content/drive/My Drive/AB_tool.csv'
df = pd.read_csv(file_path)
df

,date,country,device,continent,channel,test,test_group,event_name,value
0,2020-12-08,Palestine,desktop,Asia,Direct,4,2,new_account,1
1,2020-12-08,Palestine,desktop,Asia,Direct,3,2,new_account,1
2,2020-11-06,Puerto Rico,desktop,Americas,Social Search,2,2,new_account,1
3,2020-11-06,Puerto Rico,desktop,Americas,Social Search,1,1,new_account,1
4,2020-12-08,Croatia,desktop,Europe,Direct,4,2,new_account,1
...,...,...,...,...,...,...,...,...,...
800991,2020-12-19,Vietnam,mobile,Asia,Direct,3,2,session,1
800992,2020-12-19,Vietnam,mobile,Asia,Undefined,3,2,session,1
800993,2020-12-19,Vietnam,mobile,Asia,Organic Search,3,2,session,1
800994,2020-12-19,Vietnam,desktop,Asia,Organic Search,3,2,session,1
800995,2020-12-20,Vietnam,desktop,Asia,Direct,3,2,session,1

In [3]:
df.columns

Index(['date', 'country', 'device', 'continent', 'channel', 'test',
       'test_group', 'event_name', 'value'],
      dtype='object')

In [4]:
df['test_group'].unique()

array([2, 1])

In [5]:
df = df.rename(columns={'test': 'test_number',
                        'test_group': 'variant'})
df.head()

,date,country,device,continent,channel,test_number,variant,event_name,value
0,2020-12-08,Palestine,desktop,Asia,Direct,4,2,new_account,1
1,2020-12-08,Palestine,desktop,Asia,Direct,3,2,new_account,1
2,2020-11-06,Puerto Rico,desktop,Americas,Social Search,2,2,new_account,1
3,2020-11-06,Puerto Rico,desktop,Americas,Social Search,1,1,new_account,1
4,2020-12-08,Croatia,desktop,Europe,Direct,4,2,new_account,1

In [6]:
df['variant'] = df['variant'].map({1: 'control', 2: 'test'})
df.head()

,date,country,device,continent,channel,test_number,variant,event_name,value
0,2020-12-08,Palestine,desktop,Asia,Direct,4,test,new_account,1
1,2020-12-08,Palestine,desktop,Asia,Direct,3,test,new_account,1
2,2020-11-06,Puerto Rico,desktop,Americas,Social Search,2,test,new_account,1
3,2020-11-06,Puerto Rico,desktop,Americas,Social Search,1,control,new_account,1
4,2020-12-08,Croatia,desktop,Europe,Direct,4,test,new_account,1

In [7]:
df['event_name'].unique()

array(['new_account', 'session with orders', 'user_engagement',
       'first_visit', 'page_view', 'scroll', 'session_start', 'view_item',
       'view_promotion', 'view_search_results', 'select_item',
       'add_to_cart', 'begin_checkout', 'add_shipping_info',
       'select_promotion', 'add_payment_info', 'click', 'session',
       'view_item_list'], dtype=object)

In [8]:
events = ['add_payment_info', 'add_shipping_info', 'begin_checkout',  'new_account', 'session' ]

df = df[df['event_name'].isin(events)]
df['event_name'].unique()

array(['new_account', 'begin_checkout', 'add_shipping_info',
       'add_payment_info', 'session'], dtype=object)

In [9]:
df = df.pivot_table(index=['date', 'country', 'device', 'continent', 'channel', 'test_number', 'variant'],
                    columns='event_name', values='value', aggfunc='sum').reset_index()

df.columns.name = None

In [10]:
for col in events:
  if col not in df.columns:
    df[col] = 0

df = df.fillna(0)

print('DataSet Shape:', df.shape)

DataSet Shape: (107210, 12)

In [11]:
df.head()

,date,country,device,continent,channel,test_number,variant,add_payment_info,add_shipping_info,begin_checkout,new_account,session
0,2020-11-01,(not set),desktop,Africa,Paid Search,1,control,0.0,0.0,0.0,0.0,1.0
1,2020-11-01,(not set),desktop,Africa,Paid Search,2,control,0.0,0.0,0.0,0.0,1.0
2,2020-11-01,(not set),desktop,Americas,Direct,1,test,0.0,0.0,0.0,1.0,1.0
3,2020-11-01,(not set),desktop,Americas,Direct,2,control,0.0,0.0,0.0,1.0,1.0
4,2020-11-01,(not set),desktop,Americas,Paid Search,1,control,0.0,1.0,1.0,0.0,2.0

events = ['add_payment_info', 'add_shipping_info', 'begin_checkout',  'new_account', 'session' ]

In [12]:
metric_name = [('add_payment_info', 'session'),
           ('add_shipping_info', 'session'),
           ('begin_checkout', 'session'),
           ('new_account', 'session')]

***Порівняння пропорцій (control vs test)***


- **num_control**: кількість разів скільки подія відбулась у control;
- **den_control**: всього сесій у control;
- **num_test**: кількість разів скільки подія відбулась у test;
- **den_test**: всього сесій у test;
- **conv1, conv2**: конверсія відповідної групи;
- **p_pool**: середня пропорція по обох групах разом, для визначення оцінки розкиду даних за умови, що нульова гіпотеза правдива:
- **se**: sqrt error - помилка, наскільки сильно коливається різниця між групами через випадковість;
- **z_stat**: на скільки стандартних помилок test відрізняється від control;
- **p_value < 0.05**: True (результат значущий, зміна реальна), False (різниця могла виникнути випадково)

In [13]:
def z_test_proportion(num_control, den_control, num_test, den_test):
  conv1 = num_control / den_control if den_control > 0 else 0
  conv2 = num_test / den_test if den_test > 0 else 0

  p_pool = (num_control +num_test) / (den_control + den_test)
  se = np.sqrt(p_pool * (1 - p_pool) * (1 / den_control + 1 / den_test))

  z_stat  = (conv2 - conv1) / se if se > 0 else 0
  p_value = 1 - stats.norm.cdf(z_stat)

  return conv1, conv2, conv2 - conv1, z_stat, p_value, p_value < 0.05

# ***✅Аналіз по тесту (тотал)***

In [14]:
def cal_signif_total(data):
  group_cols = ['test_number']
  metric_cols = list({col for col, _ in metric_name } | {'session'})

# 1. Агрегація
# Просумувати всі події по групах (test_number + variant)
# Результат -  скільки разів кожна подія відбулась у control і test.
  agg = (data.groupby(group_cols + ['variant'])[metric_cols].sum().reset_index())

# 2. Розділення груп. Розділяємо зведену таблицю на дві окремі.
  control = agg[agg['variant'] == 'control'].drop(columns='variant')
  test = agg[agg['variant'] == 'test'].drop(columns='variant')

# 3. Об'єднання. Об'єднання control і test в один рядок по test_number
# Суфікси _control і _test розрізняють колонки двох груп.
  merged = control.merge(test, on=group_cols, suffixes=('_control', '_test'))

  records = []
# 4. Цикл по метрикам. Для кожної метрики з metric_name динамічно:
# 1. Беремо числівник і знаменник для control і test
# 2. Рахуємо z-test для кожного рядка
# 3. Збираємо результат у датафрейм.

  for numerator_col, denominator_col in metric_name:
        num_c = merged[f'{numerator_col}_control']
        den_c = merged[f'{denominator_col}_control']
        num_e = merged[f'{numerator_col}_test']
        den_e = merged[f'{denominator_col}_test']

# 5. Z-test для кожного рядка
# об'єднанння 4 масиви попарно і передача в z_test_proportion
# результат - список з (p1, p2, diff, z, pval, significant).
        results = [z_test_proportion(nc, dc, ne, de)
            for nc, dc, ne, de in zip(num_c, den_c, num_e, den_e)]

        res_df = pd.DataFrame(results, columns=[
            'conversion_rate_control',
            'conversion_rate_test',
            'metric_change',
            'z_stat',
            'p_value',
            'significant'])

        section_df = pd.DataFrame({
            'test_number': merged['test_number'].values,
            'metric': f'{numerator_col} / {denominator_col}',
            'numerator_event': numerator_col,
            'denominator_event': denominator_col,
            'numerator_control': num_c.values,
            'denominator_control': den_c.values,
            'conversion_rate_control': res_df['conversion_rate_control'].values,
            'numerator_test': num_e.values,
            'denominator_test': den_e.values,
            'conversion_rate_test': res_df['conversion_rate_test'].values,
            'metric_change': res_df['metric_change'].values,
            'z_stat': res_df['z_stat'].values,
            'p_value': res_df['p_value'].values,
            'significant': res_df['significant'].values})

# 6. Збір таблиці з результатом.
        records.append(section_df)

  return pd.concat(records, ignore_index=True)

In [15]:
results_total = cal_signif_total(df)
print(results_total.to_string(index=False))

 test_number                      metric   numerator_event denominator_event  numerator_control  denominator_control  conversion_rate_control  numerator_test  denominator_test  conversion_rate_test  metric_change    z_stat  p_value  significant
           1  add_payment_info / session  add_payment_info           session             1988.0              45362.0                 0.043825          2229.0           45193.0              0.049322       0.005497  3.924884 0.000043         True
           2  add_payment_info / session  add_payment_info           session             2344.0              50637.0                 0.046290          2409.0           50244.0              0.047946       0.001656  1.240994 0.107304        False
           3  add_payment_info / session  add_payment_info           session             3623.0              70047.0                 0.051722          3697.0           70439.0              0.052485       0.000763  0.643172 0.260056        False
           4  add_payment_info / session  add_payment_info           session             3731.0             105079.0                 0.035507          3601.0          105141.0              0.034249      -0.001257 -1.571106 0.941921        False
           1 add_shipping_info / session add_shipping_info           session             3034.0              45362.0                 0.066884          3221.0           45193.0              0.071272       0.004388  2.603571 0.004613         True
           2 add_shipping_info / session add_shipping_info           session             3480.0              50637.0                 0.068724          3510.0           50244.0              0.069859       0.001135  0.709557 0.238989        False
           3 add_shipping_info / session add_shipping_info           session             5298.0              70047.0                 0.075635          5188.0           70439.0              0.073652      -0.001983 -1.413727 0.921279        False
           4 add_shipping_info / session add_shipping_info           session             5128.0             105079.0                 0.048801          4956.0          105141.0              0.047137      -0.001665 -1.785795 0.962934        False
           1    begin_checkout / session    begin_checkout           session             3784.0              45362.0                 0.083418          4021.0           45193.0              0.088974       0.005556  2.978783 0.001447         True
           2    begin_checkout / session    begin_checkout           session             4262.0              50637.0                 0.084168          4313.0           50244.0              0.085841       0.001673  0.952898 0.170321        False
           3    begin_checkout / session    begin_checkout           session             9532.0              70047.0                 0.136080          9264.0           70439.0              0.131518      -0.004562 -2.511389 0.993987        False
           4    begin_checkout / session    begin_checkout           session            12555.0             105079.0                 0.119482         12267.0          105141.0              0.116672      -0.002810 -1.995998 0.977033        False
           1       new_account / session       new_account           session             3823.0              45362.0                 0.084278          3681.0           45193.0              0.081451      -0.002827 -1.542883 0.938570        False
           2       new_account / session       new_account           session             4165.0              50637.0                 0.082252          4184.0           50244.0              0.083274       0.001022  0.588793 0.278000        False
           3       new_account / session       new_account           session             5856.0              70047.0                 0.083601          5822.0           70439.0              0.082653      -0.000948 -0.643489 0.740046        False
           4       new_account / session       new_account           session             8984.0             105079.0                 0.085498          8687.0          105141.0              0.082622      -0.002875 -2.375457 0.991236        False

In [16]:
results_total.to_csv('ab_results_total.csv', index=False)
print('\n✅ Save: ab_results_total.csv')

✅ Save: ab_results_total.csv

In [17]:
files.download('ab_results_total.csv')

# ***✅Аналіз по тесту + девайсу***

In [18]:
def cal_signif_device(data):
  group_cols_device = ['test_number', 'device']
  metric_cols = list({col for col, _ in metric_name } | {'session'})

  agg_device = (data.groupby(group_cols_device + ['variant'])[metric_cols].sum().reset_index())

  control = agg_device[agg_device['variant'] == 'control'].drop(columns='variant')
  test = agg_device[agg_device['variant'] == 'test'].drop(columns='variant')

  merged = control.merge(test, on=group_cols_device, suffixes=('_control', '_test'))

  records_device = []

  for numerator_col, denominator_col in metric_name:
        num_c = merged[f'{numerator_col}_control']
        den_c = merged[f'{denominator_col}_control']
        num_e = merged[f'{numerator_col}_test']
        den_e = merged[f'{denominator_col}_test']

        results_device = [z_test_proportion(nc, dc, ne, de)
            for nc, dc, ne, de in zip(num_c, den_c, num_e, den_e)]

        res_df_device = pd.DataFrame(results_device, columns=[
            'conversion_rate_control',
            'conversion_rate_test',
            'metric_change',
            'z_stat',
            'p_value',
            'significant'])

        section_df_device = pd.DataFrame({
            'test_number': merged['test_number'].values,
            'device': merged['device'].values,
            'metric': f'{numerator_col} / {denominator_col}',
            'numerator_event': numerator_col,
            'denominator_event': denominator_col,
            'numerator_control': num_c.values,
            'denominator_control': den_c.values,
            'conversion_rate_control': res_df_device['conversion_rate_control'].values,
            'numerator_test': num_e.values,
            'denominator_test': den_e.values,
            'conversion_rate_test': res_df_device['conversion_rate_test'].values,
            'metric_change': res_df_device['metric_change'].values,
            'z_stat': res_df_device['z_stat'].values,
            'p_value': res_df_device['p_value'].values,
            'significant': res_df_device['significant'].values})

        records_device.append(section_df_device)

  return pd.concat(records_device, ignore_index=True)

In [19]:
results_device_df = cal_signif_device(df)
print(results_device_df.to_string(index=False))

 test_number  device                      metric   numerator_event denominator_event  numerator_control  denominator_control  conversion_rate_control  numerator_test  denominator_test  conversion_rate_test  metric_change    z_stat  p_value  significant
           1 desktop  add_payment_info / session  add_payment_info           session             1130.0              26467.0                 0.042695          1256.0           26417.0              0.047545       0.004850  2.686998 0.003605         True
           1  mobile  add_payment_info / session  add_payment_info           session              810.0              17896.0                 0.045262           942.0           17767.0              0.053020       0.007758  3.389330 0.000350         True
           1  tablet  add_payment_info / session  add_payment_info           session               48.0                999.0                 0.048048            31.0            1009.0              0.030723      -0.017325 -1.996608 0.977066        False
           2 desktop  add_payment_info / session  add_payment_info           session             1314.0              29497.0                 0.044547          1401.0           29380.0              0.047686       0.003139  1.815587 0.034717         True
           2  mobile  add_payment_info / session  add_payment_info           session              978.0              20017.0                 0.048858           961.0           19756.0              0.048643      -0.000215 -0.099562 0.539654        False
           2  tablet  add_payment_info / session  add_payment_info           session               52.0               1123.0                 0.046305            47.0            1108.0              0.042419      -0.003886 -0.445631 0.672068        False
           3 desktop  add_payment_info / session  add_payment_info           session             2087.0              41106.0                 0.050771          2167.0           41443.0              0.052289       0.001518  0.986051 0.162054        False
           3  mobile  add_payment_info / session  add_payment_info           session             1463.0              27404.0                 0.053386          1463.0           27423.0              0.053349      -0.000037 -0.019267 0.507686        False
           3  tablet  add_payment_info / session  add_payment_info           session               73.0               1537.0                 0.047495            67.0            1573.0              0.042594      -0.004901 -0.659106 0.745086        False
           4 desktop  add_payment_info / session  add_payment_info           session             2211.0              61484.0                 0.035961          2046.0           61436.0              0.033303      -0.002658 -2.547934 0.994582        False
           4  mobile  add_payment_info / session  add_payment_info           session             1413.0              41216.0                 0.034283          1501.0           41345.0              0.036304       0.002021  1.573870 0.057759        False
           4  tablet  add_payment_info / session  add_payment_info           session              107.0               2379.0                 0.044977            54.0            2360.0              0.022881      -0.022096 -4.198074 0.999987        False
           1 desktop add_shipping_info / session add_shipping_info           session             1711.0              26467.0                 0.064647          1916.0           26417.0              0.072529       0.007883  3.586024 0.000168         True
           1  mobile add_shipping_info / session add_shipping_info           session             1257.0              17896.0                 0.070239          1256.0           17767.0              0.070693       0.000454  0.167387 0.433533        False
           1  tablet add_shipping_info / session add_shipping_info           session               66.0                999.0                 0.066066            49.0            1009.0              0.048563      -0.017503 -1.687725 0.954268        False
           2 desktop add_shipping_info / session add_shipping_info           session             1988.0              29497.0                 0.067397          2088.0           29380.0              0.071069       0.003672  1.755041 0.039626         True
           2  mobile add_shipping_info / session add_shipping_info           session             1417.0              20017.0                 0.070790          1356.0           19756.0              0.068637      -0.002152 -0.842754 0.800317        False
           2  tablet add_shipping_info / session add_shipping_info           session               75.0               1123.0                 0.066785            66.0            1108.0              0.059567      -0.007219 -0.700617 0.758229        False
           3 desktop add_shipping_info / session add_shipping_info           session             3120.0              41106.0                 0.075901          3072.0           41443.0              0.074126      -0.001775 -0.968268 0.833545        False
           3  mobile add_shipping_info / session add_shipping_info           session             2071.0              27404.0                 0.075573          2029.0           27423.0              0.073989      -0.001584 -0.704992 0.759592        False
           3  tablet add_shipping_info / session add_shipping_info           session              107.0               1537.0                 0.069616            87.0            1573.0              0.055308      -0.014308 -1.649529 0.950480        False
           4 desktop add_shipping_info / session add_shipping_info           session             3042.0              61484.0                 0.049476          2845.0           61436.0              0.046308      -0.003168 -2.600630 0.995347        False
           4  mobile add_shipping_info / session add_shipping_info           session             1961.0              41216.0                 0.047579          2023.0           41345.0              0.048930       0.001351  0.905776 0.182527        False
           4  tablet add_shipping_info / session add_shipping_info           session              125.0               2379.0                 0.052543            88.0            2360.0              0.037288      -0.015255 -2.534313 0.994367        False
           1 desktop    begin_checkout / session    begin_checkout           session             2108.0              26467.0                 0.079646          2404.0           26417.0              0.091002       0.011356  4.673980 0.000001         True
           1  mobile    begin_checkout / session    begin_checkout           session             1593.0              17896.0                 0.089014          1561.0           17767.0              0.087860      -0.001155 -0.384029 0.649522        False
           1  tablet    begin_checkout / session    begin_checkout           session               83.0                999.0                 0.083083            56.0            1009.0              0.055500      -0.027583 -2.434631 0.992547        False
           2 desktop    begin_checkout / session    begin_checkout           session             2403.0              29497.0                 0.081466          2585.0           29380.0              0.087985       0.006519  2.840291 0.002254         True
           2  mobile    begin_checkout / session    begin_checkout           session             1766.0              20017.0                 0.088225          1656.0           19756.0              0.083823      -0.004402 -1.565423 0.941258        False
           2  tablet    begin_checkout / session    begin_checkout           session               93.0               1123.0                 0.082814            72.0            1108.0              0.064982      -0.017832 -1.609167 0.946210        False
           3 desktop    begin_checkout / session    begin_checkout           session             5618.0              41106.0                 0.136671          5567.0           41443.0              0.134329      -0.002342 -0.983009 0.837198        False
           3  mobile    begin_checkout / session    begin_checkout           session             3735.0              27404.0                 0.136294          3562.0           27423.0              0.129891      -0.006403 -2.206934 0.986341        False
           3  tablet    begin_checkout / session    begin_checkout           session              179.0               1537.0                 0.116461           135.0            1573.0              0.085823      -0.030637 -2.835304 0.997711        False
           4 desktop    begin_checkout / session    begin_checkout           session             7456.0              61484.0                 0.121267          7026.0           61436.0              0.114363      -0.006904 -3.754267 0.999913        False
           4  mobile    begin_checkout / session    begin_checkout           session             4788.0              41216.0                 0.116168          5009.0           41345.0              0.121151       0.004983  2.213611 0.013428         True
           4  tablet    begin_checkout / session    begin_checkout           session              311.0               2379.0                 0.130727           232.0            2360.0              0.098305      -0.032422 -3.503646 0.999771        False
           1 desktop       new_account / session       new_account           session             2203.0              26467.0                 0.083236          2147.0           26417.0              0.081273      -0.001962 -0.821212 0.794237        False
           1  mobile       new_account / session       new_account           session             1530.0              17896.0                 0.085494          1441.0           17767.0              0.081105      -0.004389 -1.499486 0.933126        False
           1  tablet       new_account / session       new_account           session               90.0                999.0                 0.090090            93.0            1009.0              0.092170       0.002080  0.161955 0.435671        False
           2 desktop       new_account / session       new_account           session             2442.0              29497.0                 0.082788          2385.0           29380.0              0.081178      -0.001610 -0.712176 0.761822        False
           2  mobile       new_account / session       new_account           session             1623.0              20017.0                 0.081081          1701.0           19756.0              0.086100       0.005019  1.808493 0.035265         True
           2  tablet       new_account / session       new_account           session              100.0               1123.0                 0.089047            98.0            1108.0              0.088448      -0.000600 -0.049788 0.519854        False
           3 desktop       new_account / session       new_account           session             3458.0              41106.0                 0.084124          3409.0           41443.0              0.082258      -0.001866 -0.970872 0.834194        False
           3  mobile       new_account / session       new_account           session             2272.0              27404.0                 0.082908          2276.0           27423.0              0.082996       0.000088  0.037533 0.485030        False
           3  tablet       new_account / session       new_account           session              126.0               1537.0                 0.081978           137.0            1573.0              0.087095       0.005117  0.512758 0.304060        False
           4 desktop       new_account / session       new_account           session             5314.0              61484.0                 0.086429          5105.0           61436.0              0.083095      -0.003334 -2.098595 0.982074        False
           4  mobile       new_account / session       new_account           session             3455.0              41216.0                 0.083827          3384.0           41345.0              0.081848      -0.001979 -1.031400 0.848823        False
           4  tablet       new_account / session       new_account           session              215.0               2379.0                 0.090374           198.0            2360.0              0.083898      -0.006476 -0.790263 0.785313        False

In [20]:
results_device_df.to_csv('ab_results_device.csv', index=False)
print('\n✅ Save: ab_results_device.csv')

✅ Save: ab_results_device.csv

In [21]:
files.download('ab_results_device.csv')

# ***✅Аналіз по тесту + країні***

In [24]:
def cal_signif_country(data):
  group_cols_country = ['test_number', 'country']
  metric_cols = list({col for col, _ in metric_name } | {'session'})

  agg_country = (data.groupby(group_cols_country + ['variant'])[metric_cols].sum().reset_index())

  control = agg_country[agg_country['variant'] == 'control'].drop(columns='variant')
  test = agg_country[agg_country['variant'] == 'test'].drop(columns='variant')

  merged = control.merge(test, on=group_cols_country, suffixes=('_control', '_test'))

  records_country = []

  for numerator_col, denominator_col in metric_name:
        num_c = merged[f'{numerator_col}_control']
        den_c = merged[f'{denominator_col}_control']
        num_e = merged[f'{numerator_col}_test']
        den_e = merged[f'{denominator_col}_test']

        results_country = [z_test_proportion(nc, dc, ne, de)
            for nc, dc, ne, de in zip(num_c, den_c, num_e, den_e)]

        res_df_country = pd.DataFrame(results_country, columns=[
            'conversion_rate_control',
            'conversion_rate_test',
            'metric_change',
            'z_stat',
            'p_value',
            'significant'])

        section_df_country = pd.DataFrame({
            'test_number': merged['test_number'].values,
            'country': merged['country'].values,
            'metric': f'{numerator_col} / {denominator_col}',
            'numerator_event': numerator_col,
            'denominator_event': denominator_col,
            'numerator_control': num_c.values,
            'denominator_control': den_c.values,
            'conversion_rate_control': res_df_country['conversion_rate_control'].values,
            'numerator_test': num_e.values,
            'denominator_test': den_e.values,
            'conversion_rate_test': res_df_country['conversion_rate_test'].values,
            'metric_change': res_df_country['metric_change'].values,
            'z_stat': res_df_country['z_stat'].values,
            'p_value': res_df_country['p_value'].values,
            'significant': res_df_country['significant'].values})

        records_country.append(section_df_country)

  return pd.concat(records_country, ignore_index=True)

In [25]:
results_country_df = cal_signif_country(df)
print(results_country_df.to_string(index=False))

/tmp/ipykernel_9549/900433190.py:6: RuntimeWarning: invalid value encountered in sqrt
  se = np.sqrt(p_pool * (1 - p_pool) * (1 / den_control + 1 / den_test))

 test_number              country                      metric   numerator_event denominator_event  numerator_control  denominator_control  conversion_rate_control  numerator_test  denominator_test  conversion_rate_test  metric_change    z_stat      p_value  significant
           1            (not set)  add_payment_info / session  add_payment_info           session               16.0                369.0                 0.043360            19.0             373.0              0.050938       0.007578  0.486827 3.131904e-01        False
           1              Albania  add_payment_info / session  add_payment_info           session                1.0                  9.0                 0.111111             0.0              16.0              0.000000      -0.111111 -1.360828 9.132159e-01        False
           1              Algeria  add_payment_info / session  add_payment_info           session                2.0                 29.0                 0.068966             3.0              23.0              0.130435       0.061469  0.746773 2.276003e-01        False
           1            Argentina  add_payment_info / session  add_payment_info           session                6.0                122.0                 0.049180             2.0             122.0              0.016393      -0.032787 -1.437984 9.247806e-01        False
           1              Armenia  add_payment_info / session  add_payment_info           session                0.0                  8.0                 0.000000             0.0              11.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1            Australia  add_payment_info / session  add_payment_info           session               17.0                461.0                 0.036876            16.0             427.0              0.037471       0.000594  0.046783 4.813431e-01        False
           1              Austria  add_payment_info / session  add_payment_info           session                5.0                117.0                 0.042735            12.0             125.0              0.096000       0.053265  1.620248 5.258951e-02        False
           1           Azerbaijan  add_payment_info / session  add_payment_info           session                1.0                 17.0                 0.058824             0.0              25.0              0.000000      -0.058824 -1.227378 8.901597e-01        False
           1              Bahamas  add_payment_info / session  add_payment_info           session                0.0                  6.0                 0.000000             0.0               6.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1              Bahrain  add_payment_info / session  add_payment_info           session                2.0                  6.0                 0.333333             1.0               8.0              0.125000      -0.208333 -0.940127 8.264237e-01        False
           1           Bangladesh  add_payment_info / session  add_payment_info           session                8.0                 97.0                 0.082474             4.0              89.0              0.044944      -0.037530 -1.040771 8.510092e-01        False
           1              Belarus  add_payment_info / session  add_payment_info           session                0.0                 17.0                 0.000000             0.0              13.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1              Belgium  add_payment_info / session  add_payment_info           session               13.0                184.0                 0.070652            11.0             184.0              0.059783      -0.010870 -0.422249 6.635785e-01        False
           1              Bolivia  add_payment_info / session  add_payment_info           session                0.0                  4.0                 0.000000             0.0              16.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1 Bosnia & Herzegovina  add_payment_info / session  add_payment_info           session                0.0                 13.0                 0.000000             0.0               7.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1               Brazil  add_payment_info / session  add_payment_info           session               31.0                452.0                 0.068584            25.0             446.0              0.056054      -0.012530 -0.776399 7.812432e-01        False
           1             Bulgaria  add_payment_info / session  add_payment_info           session                4.0                 62.0                 0.064516             1.0              54.0              0.018519      -0.045998 -1.216776 8.881552e-01        False
           1             Cambodia  add_payment_info / session  add_payment_info           session                0.0                 19.0                 0.000000             1.0              19.0              0.052632       0.052632  1.013423 1.554290e-01        False
           1               Canada  add_payment_info / session  add_payment_info           session              136.0               3368.0                 0.040380           194.0            3307.0              0.058663       0.018283  3.445187 2.853322e-04         True
           1                Chile  add_payment_info / session  add_payment_info           session                2.0                107.0                 0.018692             2.0              99.0              0.020202       0.001510  0.078494 4.687174e-01        False
           1                China  add_payment_info / session  add_payment_info           session               14.0                718.0                 0.019499            20.0             792.0              0.025253       0.005754  0.752652 2.258295e-01        False
           1             Colombia  add_payment_info / session  add_payment_info           session                5.0                192.0                 0.026042             9.0             206.0              0.043689       0.017648  0.954955 1.698001e-01        False
           1           Costa Rica  add_payment_info / session  add_payment_info           session                5.0                 16.0                 0.312500             0.0              23.0              0.000000      -0.312500 -2.871321 9.979562e-01        False
           1              Croatia  add_payment_info / session  add_payment_info           session                0.0                 47.0                 0.000000             0.0              47.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1               Cyprus  add_payment_info / session  add_payment_info           session                0.0                 17.0                 0.000000             0.0               8.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1              Czechia  add_payment_info / session  add_payment_info           session                6.0                115.0                 0.052174             2.0             125.0              0.016000      -0.036174 -1.559610 9.405740e-01        False
           1              Denmark  add_payment_info / session  add_payment_info           session                9.0                149.0                 0.060403             3.0             121.0              0.024793      -0.035609 -1.411987 9.210231e-01        False
           1   Dominican Republic  add_payment_info / session  add_payment_info           session                5.0                 30.0                 0.166667             1.0              25.0              0.040000      -0.126667 -1.500378 9.332417e-01        False
           1              Ecuador  add_payment_info / session  add_payment_info           session                3.0                 37.0                 0.081081             2.0              40.0              0.050000      -0.031081 -0.552995 7.098665e-01        False
           1                Egypt  add_payment_info / session  add_payment_info           session                6.0                101.0                 0.059406             3.0              85.0              0.035294      -0.024112 -0.763394 7.773858e-01        False
           1          El Salvador  add_payment_info / session  add_payment_info           session                0.0                 15.0                 0.000000             0.0              29.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1              Estonia  add_payment_info / session  add_payment_info           session                0.0                 15.0                 0.000000             1.0              14.0              0.071429       0.071429  1.053420 1.460743e-01        False
           1              Finland  add_payment_info / session  add_payment_info           session                5.0                 74.0                 0.067568             9.0              75.0              0.120000       0.052432  1.096753 1.363747e-01        False
           1               France  add_payment_info / session  add_payment_info           session               34.0                880.0                 0.038636            73.0             886.0              0.082393       0.043756  3.853720 5.816828e-05         True
           1              Georgia  add_payment_info / session  add_payment_info           session                3.0                 19.0                 0.157895             0.0              26.0              0.000000      -0.157895 -2.097259 9.820147e-01        False
           1              Germany  add_payment_info / session  add_payment_info           session               23.0                802.0                 0.028678            33.0             805.0              0.040994       0.012315  1.345999 8.915146e-02        False
           1                Ghana  add_payment_info / session  add_payment_info           session                0.0                  7.0                 0.000000             0.0              10.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1               Greece  add_payment_info / session  add_payment_info           session                4.0                152.0                 0.026316             6.0             179.0              0.033520       0.007204  0.381566 3.513918e-01        False
           1            Guatemala  add_payment_info / session  add_payment_info           session                2.0                 15.0                 0.133333             0.0              12.0              0.000000      -0.133333 -1.314534 9.056667e-01        False
           1             Honduras  add_payment_info / session  add_payment_info           session                0.0                  3.0                 0.000000             0.0               9.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1            Hong Kong  add_payment_info / session  add_payment_info           session               17.0                294.0                 0.057823            28.0             281.0              0.099644       0.041821  1.866427 3.099084e-02         True
           1              Hungary  add_payment_info / session  add_payment_info           session                0.0                 53.0                 0.000000             5.0              60.0              0.083333       0.083333  2.149684 1.579010e-02         True
           1              Iceland  add_payment_info / session  add_payment_info           session                0.0                  8.0                 0.000000             1.0               6.0              0.166667       0.166667  1.198289 1.154022e-01        False
           1                India  add_payment_info / session  add_payment_info           session              202.0               4291.0                 0.047075           230.0            4263.0              0.053953       0.006877  1.452342 7.320332e-02        False
           1            Indonesia  add_payment_info / session  add_payment_info           session               12.0                431.0                 0.027842            20.0             432.0              0.046296       0.018454  1.434507 7.571388e-02        False
           1                 Iraq  add_payment_info / session  add_payment_info           session                1.0                 32.0                 0.031250             0.0              15.0              0.000000      -0.031250 -0.692055 7.555486e-01        False
           1              Ireland  add_payment_info / session  add_payment_info           session                7.0                254.0                 0.027559            23.0             250.0              0.092000       0.064441  3.057132 1.117328e-03         True
           1               Israel  add_payment_info / session  add_payment_info           session               10.0                206.0                 0.048544            13.0             209.0              0.062201       0.013657  0.607978 2.716011e-01        False
           1                Italy  add_payment_info / session  add_payment_info           session               10.0                625.0                 0.016000            29.0             616.0              0.047078       0.031078  3.137500 8.519773e-04         True
           1              Jamaica  add_payment_info / session  add_payment_info           session                0.0                  9.0                 0.000000             0.0              13.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1                Japan  add_payment_info / session  add_payment_info           session               43.0                578.0                 0.074394            51.0             649.0              0.078582       0.004188  0.275317 3.915363e-01        False
           1               Jordan  add_payment_info / session  add_payment_info           session                0.0                 29.0                 0.000000             0.0              36.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1           Kazakhstan  add_payment_info / session  add_payment_info           session                0.0                 22.0                 0.000000             1.0              29.0              0.034483       0.034483  0.879655 1.895231e-01        False
           1                Kenya  add_payment_info / session  add_payment_info           session                1.0                 29.0                 0.034483             0.0              23.0              0.000000      -0.034483 -0.899252 8.157408e-01        False
           1               Kosovo  add_payment_info / session  add_payment_info           session                0.0                  8.0                 0.000000             0.0               2.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1               Kuwait  add_payment_info / session  add_payment_info           session                0.0                 26.0                 0.000000             5.0              24.0              0.208333       0.208333  2.453267 7.078263e-03         True
           1               Latvia  add_payment_info / session  add_payment_info           session                1.0                 20.0                 0.050000             3.0              25.0              0.120000       0.070000  0.819912 2.061331e-01        False
           1              Lebanon  add_payment_info / session  add_payment_info           session                6.0                 15.0                 0.400000             0.0              17.0              0.000000      -0.400000 -2.892962 9.980919e-01        False
           1            Lithuania  add_payment_info / session  add_payment_info           session                0.0                 60.0                 0.000000             0.0              57.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1           Luxembourg  add_payment_info / session  add_payment_info           session                0.0                  8.0                 0.000000             0.0              11.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1                Macao  add_payment_info / session  add_payment_info           session                2.0                 10.0                 0.200000             0.0               6.0              0.000000      -0.200000 -1.171080 8.792167e-01        False
           1             Malaysia  add_payment_info / session  add_payment_info           session               12.0                253.0                 0.047431            15.0             245.0              0.061224       0.013794  0.679587 2.483830e-01        False
           1                Malta  add_payment_info / session  add_payment_info           session                1.0                 12.0                 0.083333             1.0              15.0              0.066667      -0.016667 -0.164317 5.652591e-01        False
           1               Mexico  add_payment_info / session  add_payment_info           session               15.0                393.0                 0.038168            15.0             374.0              0.040107       0.001939  0.138457 4.449395e-01        False
           1             Mongolia  add_payment_info / session  add_payment_info           session                0.0                 10.0                 0.000000             1.0              12.0              0.083333       0.083333  0.934353 1.750609e-01        False
           1              Morocco  add_payment_info / session  add_payment_info           session                1.0                 81.0                 0.012346             3.0              68.0              0.044118       0.031772  1.195144 1.160154e-01        False
           1      Myanmar (Burma)  add_payment_info / session  add_payment_info           session                0.0                 13.0                 0.000000             0.0              29.0              0.000000       0.000000  0.000000 5.000000e-01        False
           1                Nepal  add_payment_info / session  add_payment_info           session                0.0                 10.0                 0.000000             1.0              20.0              0.050000       0.050000  0.719195 2.360104e-01        False
           1          Netherlands  add_payment_info / session  add_payment_info           session               32.0                526.0                 0.060837            30.0             526.0              0.057034      -0.003802 -0.261833 6.032749e-01        False
           1          New Zealand  add_payment_info / session  add_payment_info           session                2.0                 48.0                 0.041667             5.0              68.0              0.073529       0.031863  0.709782 2.389197e-01        False
           1              Nigeria  add_payment_info / session  add_payment_info           session                4.0                 69.0                 0.057971            10.0              85.0              0.117647       0.059676  1.281051 1.000879e-01        False
           1      North Macedonia  add_payment_info / session  add_payment_info           session                3.0                 23.0                 0.130435             4.0              22.0              0.181818       0.051383  0.475405 3.172493e-01        False
           1               Norway  add_payment_info / session  add_payment_info           session                1.0                 96.0                 0.010417             0.0              58.0              0.000000      -0.010417 -0.779818 7.822509e-01        False

In [ ]:
results_country_df.to_csv('ab_results_country.csv', index=False)
print('\n✅ Save: ab_results_country.csv')

In [ ]:
files.download('ab_results_country.csv')